#!/bin/bash

CL="\033[0m"
BYE="\033[1;33m"
SELECT=$BYE
log() {
    echo -ne $SELECT
    echo -e "$@"
    echo -ne $CL
}

log "请将本atop目录放到/data/目录下"
if [[ `pwd` != "/data/atop" ]];then
    exit
fi
yum -y install atop

log "创建目录"
mkdir tmp logs
cd tmp

log "请下载好对应的内核版本，放到本/data/atop/tmp目录里"
uname -a|awk '{print $3}'
log "下载好后按任意键继续"
read

log "复制内核源码包"
rpm2cpio ./*.rpm|cpio -idm
cp -r ./usr /

# 注意内核版本，如果大于3.17或小于3.10，不能用这个
log "下载安装netatop依赖"
wget https://www.atoptool.nl/download/netatop-0.3.tar.gz
tar xzf netatop-0.3.tar.gz
cd netatop-0.3
make
make install
service netatop start

echo ""
log "请添加crontab"
log "# 每十秒记录一次atop日志，保存七天(一次运行一小时）"
log "0 * * * * cd /data/atop/; ./run >>./cron.log 2>&1"
