#!/bin/bash

config_file=/sys/class/backlight/intel_backlight/brightness

step=40
now=`cat $config_file`
#if [[ $now -lt 51 ]];then
#	step=25
#fi

if [[ $1 == "up" ]];then
	if [[ $now -gt 650 ]];then
		echo "too light: $now"
		exit
	fi
	new=`expr $now + $step`
	echo $new >$config_file
elif [[ $1 == "down" ]];then
	if [[ $now -lt 41 ]];then
		echo "40" >$config_file
		echo "too dark: $now"
		exit
	fi
	new=`expr $now - $step`
	echo $new >$config_file
fi

echo -n `cat $config_file`
echo "/700"
