#!/bin/bash

# yum 安装依赖软件
if [[ `which yum` ]]; then
    echo "================================== yum安装依赖"
    rpmdb --rebuilddb
    yum install -y curl wget tar gcc zlib-devel openssl openssl-devel \
        bzip2-devel git tar pcre-devel xz-devel automake unzip ncurses-devel \
        libpcap-devel glib2-devel python-devel
    yum clean all
fi

# 安装pip
if [[ ! `which pip` ]]; then
    echo "================================== 安装pip"
    cd /tmp && \
    wget http://mirrors.aliyun.com/pypi/packages/6b/dd/a7de8caeeffab76bacf56972b3f090c12e0ae6932245abbce706690a6436/setuptools-28.3.0.tar.gz && \
    tar -zxvf setuptools-28.3.0.tar.gz && \
    cd setuptools-28.3.0 && \
    python setup.py install && \
    wget http://mirrors.aliyun.com/pypi/packages/e7/a8/7556133689add8d1a54c0b14aeff0acb03c64707ce100ecd53934da1aa13/pip-8.1.2.tar.gz && \
    tar -xzvf pip-8.1.2.tar.gz && \
    cd pip-8.1.2 && \
    python setup.py install && \
    pip install --upgrade pip
fi

# 安装ncdu
if [[ ! `which ncdu` ]]; then
    echo "================================== 安装 ncdu"
    rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
    yum install -y ncdu
fi

# 安装ag命令
if [[ ! `which ag` ]]; then
    echo "================================== 安装 the_silver_searcher"
    cd /tmp/
    git clone https://github.com/ggreer/the_silver_searcher.git ./ag
    cd ag
    ./build.sh
    sudo make install
    ln `which ag` /usr/bin
fi

# 安装proxychains命令
if [[ ! `which proxychains4` ]]; then
    echo "================================== 安装 proxychains"
    cd /tmp/
    git clone https://github.com/rofl0r/proxychains-ng proxychains
    cd proxychains
    ./configure --prefix=/usr --sysconfdir=/etc
    make
    make install
    make install-config
    cd .. && rm -rf proxychains
fi

# 其他python命令
which glances || pip install Glances







