#!/bin/bash

path=`pwd`

# yum 安装依赖软件
if [[ `which yum` ]]; then
    echo "================================== yum安装依赖"
    rpmdb --rebuilddb
    yum install -y curl wget tar gcc zlib-devel openssl openssl-devel \
        bzip2-devel git tar
    yum clean all
fi

# 安装pip
if [[ ! `which pip` ]]; then
    echo "================================== 安装pip"
    cd /tmp && \
    wget http://mirrors.aliyun.com/pypi/packages/6b/dd/a7de8caeeffab76bacf56972b3f090c12e0ae6932245abbce706690a6436/setuptools-28.3.0.tar.gz && \
    tar -zxvf setuptools-28.3.0.tar.gz && \
    cd setuptools-28.3.0 && \
    python setup.py install && \
    wget http://mirrors.aliyun.com/pypi/packages/e7/a8/7556133689add8d1a54c0b14aeff0acb03c64707ce100ecd53934da1aa13/pip-8.1.2.tar.gz && \
    tar -xzvf pip-8.1.2.tar.gz && \
    cd pip-8.1.2 && \
    python setup.py install && \
    pip install --upgrade pip
fi

cd $path

echo "#!/bin/bash
#enviroment config

TINYPATH=$path
PATH=\$PATH:\$TINYPATH:\$TINYPATH/nginx:\$TINYPATH/third-party/kprdbg:\$TINYPATH/raspberry:

export TINYPATH
export PATH
"> tinybashrc

cp ./bashrc ~/.bashrc
cp ./inputrc ~/.inputrc

check=`cat ~/.bashrc|grep tinybashrc`
if [[ ! $check ]];then
	echo "" >>~/.bashrc
	echo "#tiny command. by astraylinux" >>~/.bashrc
	echo "source $path/tinybashrc" >>~/.bashrc
fi
