#!/bin/bash

path=`pwd`

echo "#!/bin/bash
#enviroment config

TINYPATH=$path
PATH=\$PATH:\$TINYPATH:\$TINYPATH/nginx:\$TINYPATH/python:\$TINYPATH/raspberry:\$TINYPATH/hardware:\$TINYPATH/mysql

export TINYPATH
export PATH
"> tinybashrc

cp ./bashrc ~/.bashrc
cp ./inputrc ~/.inputrc

check=`cat ~/.bashrc|grep tinybashrc`
if [[ ! $check ]];then
	echo "" >>~/.bashrc
	echo "#tiny command. by astraylinux" >>~/.bashrc
	echo "source $path/tinybashrc" >>~/.bashrc
fi
