#!/bin/bash

if [[ $1 ]];then
    ps ax|grep --color "$1"
    kill -9 `ps ax|grep "$1"|grep -v 'mykill'|grep -v grep|awk '{print $1}'`
    echo "================================================================================ After"
    ps ax|grep --color "$1"
else
    echo "[ERROR]: need filter key."
fi
