#!/bin/bash

function redis_start(){
	cd /usr/local/redis/bin
	./redis-server ../etc/redis.conf >>../log/redis.log 2>&1 &
	sleep 1
	pid=$(ps ax |grep 'redis-server'|grep -v 'grep'|awk '{print $1}')
	echo "start redis-server: $pid"
}

function redis_stop(){
	pid=$(ps ax |grep 'redis-server'|grep -v 'grep'|awk '{print $1}')
	kill -9 $pid
	echo "stop redis-server: $pid"
}

if [[ $1 == "start" ]];then
	redis_start
elif [[ $1 == "restart" ]];then
	redis_stop
	redis_start
elif [[ $1 == "stop" ]];then
	redis_stop
fi
