#!/bin/bash

cat $0

#下面是字体输出颜色及终端格式控制
#字体色范围：30-37
CL="\033[0m"
BL="\033[30m"
RD="\033[31m"
GR="\033[32m"
YE="\033[33m"
BU="\033[34m"
PE="\033[35m"
SB="\033[36m"
WI="\033[37m"
BBL="\033[1;30m"
BRD="\033[1;31m"
BGR="\033[1;32m"
BYE="\033[1;33m"
BBU="\033[1;34m"
BPE="\033[1;35m"
BSB="\033[1;36m"
BWI="\033[1;37m"
GBL="\033[40m"
GRD="\033[41m"
GGR="\033[42m"
GYE="\033[43m"
GBU="\033[44m"
GPE="\033[45m"
GSB="\033[46m"
GWI="\033[47m"

SELECT=$RD
log() {
    echo -en $SELECT
    echo -e $@
    echo -en $CL
}

echo -e "BL:$BL 黑色字 $CL"
echo -e "RD:$RD 红色字 $CL"
echo -e "GR:$GR 绿色字 $CL"
echo -e "YE:$YE 黄色字 $CL"
echo -e "BU:$BU 蓝色字 $CL"
echo -e "YE:$PE 紫色字 $CL"
echo -e "SB:$SB 天蓝字 $CL"
echo -e "WI:$WI 白色字 $CL"
echo -e "BBL:$BBL 黑色字 $CL"
echo -e "BRD:$BRD 红色字 $CL"
echo -e "BGR:$BGR 绿色字 $CL"
echo -e "BYE:$BYE 黄色字 $CL"
echo -e "BBU:$BBU 蓝色字 $CL"
echo -e "BPE:$BPE 紫色字 $CL"
echo -e "BSB:$BSB 天蓝字 $CL"
echo -e "BWI:$BWI 白色字 $CL"
echo -e "GBL:$GBL 黑底 $CL"
echo -e "GRD:$GRD 红底 $CL"
echo -e "GGR:$GGR 绿底 $CL"
echo -e "GYE:$GYE 黄底 $CL"
echo -e "GBU:$GBU 蓝底 $CL"
echo -e "GPE:$GPE 紫底 $CL"
echo -e "GSB:$GSB 天蓝 $CL"
echo -e "GWI:$GWI 白底 $CL"

#echo -e "\033[40;37m 黑底白字 \033[0m"
#控制选项说明
#\033[0m 关闭所有属性
#\033[1m 设置高亮度
#\033[4m 下划线
#echo -e "\033[4;31m 下划线红字 \033[0m"

#闪烁
#echo -e "\033[5;34m 红字在闪烁 \033[0m"
#反影
#echo -e "\033[8m 消隐 \033[0m "

#\033[30m-\033[37m 设置前景色
#\033[40m-\033[47m 设置背景色
#\033[nA光标上移n行
#\033[nB光标下移n行
#echo -e "\033[4A 光标上移4行 \033[0m"

#\033[nC光标右移n行
#\033[nD光标左移n行
#\033[y;xH设置光标位置
#\033[2J清屏
#\033[K清除从光标到行尾的内容
#echo -e "\033[K 清除光标到行尾的内容 \033[0m"

#\033[s 保存光标位置
#\033[u 恢复光标位置
#\033[?25| 隐藏光标
#\033[?25h 显示光标
#echo -e "\033[?25l 隐藏光标 \033[0m"
#echo -e "\033[?25h 显示光标 \033[0m"
