#!/bin/bash

function _start(){
	ssserver -c /etc/shadowsocks.json -d start
}

function _stop(){
	pids=`ps ax |grep "ssserver -c /etc/shadowsocks.json"|awk '{print $1}'`
	echo $pids
	kill -9 $pids
}

function _restart(){
	_stop
	_start
}

if [[ $1 == "start" ]];then
	_start
elif [[ $1 == "stop" ]];then
	_stop
elif [[ $1 == "restart" ]];then
	_restart
fi
