#!/bin/bash 

if [[ -d ~/git/tiny-command ]];then
    cd ~/git/tiny-command
    git pull
fi

if [[ -d ~/git/pylib ]];then
    cd ~/git/pylib
    git pull
fi


if [[ -d ~/git/vim-pkg ]];then
    cd ~/git/vim-pkg
    git pull
fi


