#!/bin/bash

filename=./fiotest.data

dd if=/dev/zero of=$filename bs=200M count=10 conv=fdatasync

echo "====================================================== 顺序读："
fio -filename=$filename -zero_buffers -direct=1 -iodepth 1 -thread -rw=read -ioengine=psync -bs=4k -size=1G -numjobs=30 -runtime=20 -group_reporting -name=mytest|grep iops

echo "====================================================== 顺序写："
fio -filename=$filename -zero_buffers -direct=1 -iodepth 1 -thread -rw=write -ioengine=psync -bs=4k -size=1G -numjobs=30 -runtime=20 -group_reporting -name=mytest|grep iops

echo "====================================================== 随机读："
fio -filename=$filename -zero_buffers -direct=1 -iodepth 1 -thread -rw=randread -ioengine=psync -bs=4k -size=1G -numjobs=30 -runtime=20 -group_reporting -name=mytest|grep iops

echo "====================================================== 随机写："
fio -filename=$filename -zero_buffers -direct=1 -iodepth 1 -thread -rw=randwrite -ioengine=psync -bs=4k -size=1G -numjobs=30 -runtime=20 -group_reporting -name=mytest|grep iops

echo "====================================================== 混合随机读写："
fio -filename=$filename -zero_buffers -direct=1 -iodepth 1 -thread -rw=randrw -rwmixread=70 -ioengine=psync -bs=4k -size=1G -numjobs=30 -runtime=20 -group_reporting -name=mytest -ioscheduler=noop|grep iops

rm $filename
