#!/bin/bash


cd /usr/local/src/
wget http://res.astraylinux.com/soft/vim/vim-7.3.tar.bz2
tar jxvf vim-7.3.tar.bz2

cd vim73/
#--enable-multibyte开启多字符编码，必选，不然VIM中文乱码。
./configure --prefix=/usr/local/vim --enable-multibyte

make
make install

echo "======================================================================="
echo "add next line to you .bashrc or delete old vim and create a soft link"
echo "alias vim='/usr/local/vim/bin/vim'"

cd ../
rm -rf vim73 vim-7.3.tar.bz2
